"""
data/phase9_empirical/render_visualization.py
==============================================

Render a one-page-per-decade PDF visualizing the empirical target KDEs
alongside the per-source synthetic point clouds.

Augmentation pass adds:
  - per-decade page now shows BOTH typology-derived and raw-style
    point clouds with distinct color schemes.
  - a "before vs after augmentation" comparison strip page that
    overlays the pre-augmentation (Pew + Hidden Tribes only) KDE
    against the post-augmentation (raw + typology) KDE per decade.
  - correlation trajectory plot before/after.

Output: D:\\MyApps\\ABM\\docs\\results\\phase9_empirical_targets_visualization.pdf
"""

import os
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

from build_empirical_targets import (
    DECADE_SOURCES,
    build_decade,
    GRID_RANGE,
    GRID_N,
    RAW_DECADE_WEIGHTS,
    RAW_DECADE_SOURCES,
)


OUT_PDF = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", "docs", "results", "phase9_empirical_targets_visualization.pdf")
)
PREAUG_DIR = os.path.dirname(os.path.abspath(__file__))


def load_preaug(decade):
    z = np.load(os.path.join(PREAUG_DIR, f"phase9_empirical_kde_{decade}_preaug.npy"))
    pts = np.load(os.path.join(PREAUG_DIR, f"phase9_empirical_pointcloud_{decade}_preaug.npy"))
    return z, pts


def compute_corr(pts):
    if len(pts) < 2:
        return float("nan")
    return float(np.corrcoef(pts[:, 0], pts[:, 1])[0, 1])


def main():
    decades = sorted(DECADE_SOURCES.keys())
    builds = {d: build_decade(d) for d in decades}
    z_max = max(b["Z"].max() for b in builds.values())

    with PdfPages(OUT_PDF) as pdf:
        # Cover
        fig, ax = plt.subplots(figsize=(8.5, 11))
        ax.axis("off")
        title = "polarlab Phase 9 -- Empirical Target Distributions per Decade (AUGMENTED)"
        subtitle = (
            "Per-decade 2D KDE of US voter ideology positions on the "
            "economic x cultural compass [-1, 1]^2.\n"
            "AUGMENTED: combines Pew Political Typology + Hidden Tribes 2018 (typology side)\n"
            "with ANES + GSS + CCES + DW-NOMINATE elite raw-data-style synthetic clouds.\n\n"
            "Augmentation rationale: the original Pew typology centroids inflate\n"
            "the within-population x<->y correlation because Pew's k-means clustering\n"
            "is designed to produce ideologically coherent groups. Adding raw-style\n"
            "point clouds anchored to published moments from ANES/GSS/CCES dilutes\n"
            "this artifact to literature-faithful values (e.g. 2000 corr drops from\n"
            "0.61 to ~0.37, vs Treier-Hillygus 2009 ANES-derived 0.30).\n\n"
            "Per-decade re-weighting: raw-style sources get 60-70% of combined cloud;\n"
            "typology sources get 30-40%. CCES contributes 2010+ only.\n\n"
            "Each decade page shows: top-left KDE heatmap, top-right contours with\n"
            "raw points (blue) and typology points (orange) distinguished,\n"
            "bottom-left source composition, bottom-right marginals.\n\n"
            "Comparison strip page shows pre-augmentation (Pew-only) vs post-augmentation KDE.\n"
            "Correlation trajectory plot shows the artifact dilution per decade.\n\n"
            "Axes: x = economic (-1 redistributive .. +1 laissez-faire),\n"
            "y = social/cultural (-1 progressive/secular .. +1 traditional/restrictive).\n\n"
            "Methodology: phase9_empirical_targets.md\n"
            "Augmentation notes: augmentation_notes.md\n"
            "Raw .npy files: phase9_data/phase9_empirical_kde_<decade>.npy\n"
            "Pre-augmentation snapshots: phase9_data/phase9_empirical_kde_<decade>_preaug.npy\n\n"
            "Generated by phase9_data/render_visualization.py."
        )
        ax.text(0.05, 0.95, title, fontsize=13, fontweight="bold", va="top")
        ax.text(0.05, 0.88, subtitle, fontsize=9, va="top", wrap=True)
        pdf.savefig(fig)
        plt.close(fig)

        # Per-decade pages
        for d in decades:
            b = builds[d]
            X, Y, Z = b["X"], b["Y"], b["Z"]
            combined = b["combined_points"]
            raw_combined = b["raw_combined"]
            typ_combined = b["typ_combined"]
            per_source = b["per_source"]
            typ_sources = DECADE_SOURCES[d]
            raw_sources = RAW_DECADE_SOURCES[d]
            raw_weight = b["raw_weight"]

            fig = plt.figure(figsize=(11, 8.5))
            fig.suptitle(
                f"Decade {d}  --  {len(typ_sources)} typology + {len(raw_sources)} raw source(s),  "
                f"{b['n_typ']} typ pts + {b['n_raw']} raw pts = {len(combined)} combined  "
                f"(raw weight = {raw_weight:.0%})",
                fontsize=11, fontweight="bold",
            )

            # (1) KDE heatmap
            ax1 = fig.add_subplot(2, 2, 1)
            im = ax1.imshow(
                Z, origin="lower",
                extent=[GRID_RANGE[0], GRID_RANGE[1], GRID_RANGE[0], GRID_RANGE[1]],
                cmap="viridis", aspect="equal", vmin=0, vmax=z_max,
            )
            ax1.axhline(0, color="white", lw=0.5, alpha=0.5)
            ax1.axvline(0, color="white", lw=0.5, alpha=0.5)
            ax1.set_title(f"Augmented KDE  corr(x,y)={compute_corr(combined):+.2f}", fontsize=10)
            ax1.set_xlabel("economic")
            ax1.set_ylabel("social / cultural")
            fig.colorbar(im, ax=ax1, fraction=0.046, pad=0.04)

            # (2) Contours + raw-vs-typology overlay
            ax2 = fig.add_subplot(2, 2, 2)
            ax2.contour(X, Y, Z, levels=8, cmap="Greys", alpha=0.6)
            if len(raw_combined) > 0:
                ridx = np.random.default_rng(42).choice(
                    len(raw_combined), min(600, len(raw_combined)), replace=False)
                ax2.scatter(raw_combined[ridx, 0], raw_combined[ridx, 1],
                            s=2, alpha=0.30, color="C0",
                            label=f"raw (ANES/GSS/CCES/DWNOM) n={len(raw_combined)}")
            tidx = np.random.default_rng(43).choice(
                len(typ_combined), min(400, len(typ_combined)), replace=False)
            ax2.scatter(typ_combined[tidx, 0], typ_combined[tidx, 1],
                        s=2, alpha=0.35, color="C1",
                        label=f"typology (Pew/HT) n={len(typ_combined)}")
            ax2.set_xlim(*GRID_RANGE)
            ax2.set_ylim(*GRID_RANGE)
            ax2.axhline(0, color="black", lw=0.5, alpha=0.3)
            ax2.axvline(0, color="black", lw=0.5, alpha=0.3)
            ax2.set_aspect("equal")
            ax2.set_title("Raw (blue) vs typology (orange) point clouds")
            ax2.set_xlabel("economic")
            ax2.set_ylabel("social / cultural")
            ax2.legend(fontsize=7, loc="upper right")

            # (3) Source composition table
            ax3 = fig.add_subplot(2, 2, 3)
            ax3.axis("off")
            lines = []
            lines.append(f"DECADE {d} composition (raw weight = {raw_weight:.0%}):")
            lines.append("")
            lines.append("--- Typology sources ---")
            for name, typology, sd in typ_sources:
                lines.append(f"  {name}  (SD={sd:.2f}, downsampled to {b['n_typ']} total typ pts)")
            lines.append("")
            lines.append("--- Raw-style sources ---")
            for name, fn, weight in raw_sources:
                n_pts = len(per_source.get(name, []))
                if n_pts > 0:
                    lines.append(f"  {name:<22s}  within-raw weight={weight:.2f}  n={n_pts}")
                else:
                    lines.append(f"  {name:<22s}  N/A this decade")
            lines.append("")
            lines.append("--- Diagnostics ---")
            lines.append(f"  combined corr(x,y) = {compute_corr(combined):+.4f}")
            lines.append(f"  raw-only  corr(x,y) = {compute_corr(raw_combined):+.4f}")
            lines.append(f"  typ-only  corr(x,y) = {compute_corr(typ_combined):+.4f}")
            lines.append(f"  combined var(x) = {combined[:,0].var():.3f}")
            lines.append(f"  combined var(y) = {combined[:,1].var():.3f}")
            lines.append(f"  combined mean|x| = {np.abs(combined[:,0]).mean():.3f}")
            ax3.text(0.0, 1.0, "\n".join(lines),
                     fontsize=7, family="monospace", va="top")

            # (4) Marginals
            ax4 = fig.add_subplot(2, 2, 4)
            bins = np.linspace(*GRID_RANGE, 40)
            ax4.hist(combined[:, 0], bins=bins, density=True, alpha=0.4,
                     color="C0", label="economic (x)")
            ax4.hist(combined[:, 1], bins=bins, density=True, alpha=0.4,
                     color="C3", label="social (y)")
            ax4.axvline(0, color="black", lw=0.5, alpha=0.4)
            ax4.set_xlim(*GRID_RANGE)
            ax4.set_title("Marginal histograms (combined cloud)")
            ax4.set_xlabel("compass position")
            ax4.set_ylabel("density")
            ax4.legend(fontsize=8)

            fig.tight_layout(rect=(0, 0, 1, 0.96))
            pdf.savefig(fig)
            plt.close(fig)

        # Trajectory page
        fig, axes = plt.subplots(1, 5, figsize=(15, 4), sharey=True)
        for ax, d in zip(axes, decades):
            b = builds[d]
            im = ax.imshow(
                b["Z"], origin="lower",
                extent=[GRID_RANGE[0], GRID_RANGE[1], GRID_RANGE[0], GRID_RANGE[1]],
                cmap="viridis", aspect="equal", vmin=0, vmax=z_max,
            )
            ax.axhline(0, color="white", lw=0.5, alpha=0.5)
            ax.axvline(0, color="white", lw=0.5, alpha=0.5)
            ax.set_title(f"{d}\ncorr={compute_corr(b['combined_points']):+.2f}", fontsize=10)
            ax.set_xlabel("econ")
        axes[0].set_ylabel("social")
        fig.suptitle("Augmented KDE trajectory 1980 -> 2020 (shared colorbar)", fontsize=12)
        fig.colorbar(im, ax=axes, fraction=0.02, pad=0.02)
        pdf.savefig(fig)
        plt.close(fig)

        # Before vs after comparison strip
        try:
            preaug_data = {d: load_preaug(d) for d in decades}
            have_preaug = True
        except FileNotFoundError as e:
            print(f"Skipping pre-aug comparison page: {e}")
            have_preaug = False

        if have_preaug:
            pre_zmax = max(preaug_data[d][0].max() for d in decades)
            shared_zmax = max(pre_zmax, z_max)

            fig, axes = plt.subplots(2, 5, figsize=(15, 7), sharex=True, sharey=True)
            for col, d in enumerate(decades):
                pre_z, pre_pts = preaug_data[d]
                post_z = builds[d]["Z"]
                post_pts = builds[d]["combined_points"]

                ax_pre = axes[0, col]
                ax_pre.imshow(pre_z, origin="lower",
                              extent=[GRID_RANGE[0], GRID_RANGE[1], GRID_RANGE[0], GRID_RANGE[1]],
                              cmap="viridis", aspect="equal", vmin=0, vmax=shared_zmax)
                ax_pre.axhline(0, color="white", lw=0.5, alpha=0.5)
                ax_pre.axvline(0, color="white", lw=0.5, alpha=0.5)
                pre_corr = compute_corr(pre_pts)
                ax_pre.set_title(f"{d}  PRE\ncorr={pre_corr:+.2f}", fontsize=10)

                ax_post = axes[1, col]
                im = ax_post.imshow(post_z, origin="lower",
                                    extent=[GRID_RANGE[0], GRID_RANGE[1], GRID_RANGE[0], GRID_RANGE[1]],
                                    cmap="viridis", aspect="equal", vmin=0, vmax=shared_zmax)
                ax_post.axhline(0, color="white", lw=0.5, alpha=0.5)
                ax_post.axvline(0, color="white", lw=0.5, alpha=0.5)
                post_corr = compute_corr(post_pts)
                ax_post.set_title(f"{d}  POST\ncorr={post_corr:+.2f}", fontsize=10)
                ax_post.set_xlabel("econ")

            axes[0, 0].set_ylabel("PRE-aug\n(Pew + HT only)\nsocial")
            axes[1, 0].set_ylabel("POST-aug\n(+ ANES/GSS/CCES/DWNOM)\nsocial")
            fig.suptitle(
                "Before vs After Augmentation -- per-decade KDE comparison\n"
                "(PRE was Pew-typology-heavy and inflated x-y correlation; "
                "POST dilutes with raw-data-anchored moment-matched clouds)",
                fontsize=11,
            )
            fig.colorbar(im, ax=axes, fraction=0.015, pad=0.02)
            pdf.savefig(fig)
            plt.close(fig)

            # Correlation trajectory
            fig, ax = plt.subplots(figsize=(8, 5))
            pre_corrs = [compute_corr(preaug_data[d][1]) for d in decades]
            post_corrs = [compute_corr(builds[d]["combined_points"]) for d in decades]
            ax.plot(decades, pre_corrs, "o-", color="C3", lw=2, ms=8,
                    label="Pre-augmentation (Pew + HT)")
            ax.plot(decades, post_corrs, "s-", color="C0", lw=2, ms=8,
                    label="Post-augmentation (+ raw)")
            ax.scatter([2000], [0.30], marker="*", color="black", s=150,
                       label="Treier-Hillygus 2009 ANES 2000 (target)")
            ax.plot([1980, 1990, 2000, 2010, 2020], [0.20, 0.25, 0.30, 0.40, 0.55],
                    "--", color="gray", lw=1.2, alpha=0.7,
                    label="Levendusky/Mason sorting reference")
            ax.set_xlabel("decade")
            ax.set_ylabel("corr(x_econ, y_social)")
            ax.set_title("Cross-axis correlation: pre vs post augmentation\n"
                         "(closer to literature-measured = better)")
            ax.grid(alpha=0.3)
            ax.legend(fontsize=8, loc="upper left")
            ax.set_xticks(decades)
            ax.set_ylim(0, 0.85)
            fig.tight_layout()
            pdf.savefig(fig)
            plt.close(fig)

    print(f"Wrote {OUT_PDF}")


if __name__ == "__main__":
    main()
